name: Release
on:
  push:
    branches:
      - master

jobs:
  semantic-version:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Semantic Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Install
        run: |
          mv package.json ignore.package.json
          npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
          mv ignore.package.json package.json
      - name: Versioning
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --provider=github
